[env:stm32f407zgt6_tf_reader]
platform = ststm32
board = black_f407zg
framework = stm32cube

upload_protocol = cmsis-dap
debug_tool = cmsis-dap
monitor_speed = 115200

board_build.stm32cube.custom_config_header = yes

build_flags =
  -DSTM32F407xx
  -DUSE_HAL_DRIVER
  -Iinclude

extra_scripts =
  pre:extra_scripts/build_fatfs.py
